/**
 * MiFirma — tipos de la base, generados por introspección.
 *
 * NO editar a mano: se regenera desde el esquema real con
 *
 *   DATABASE_URL="$MIFIRMA_DB" \\
 *     npx kysely-codegen --dialect postgres --out-file src/db/schema.ts
 *
 * Cubre las migraciones 001 a 017. Las particiones de `bitacora_plataforma` no
 * aparecen a propósito: se escribe y se lee siempre por la tabla padre.
 */

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AnclajeIdentidad {
  creado_en: Generated<Timestamp>;
  documento_numero_norm: string | null;
  documento_tipo: string | null;
  emisor: string | null;
  evidencia_id: string | null;
  id: Generated<string>;
  identidad_id: string;
  idp: string | null;
  idp_sujeto: string | null;
  metodo_prueba: string;
  nivel_garantia: string;
  pais: string | null;
  probado_en: Generated<Timestamp>;
  revocado_en: Timestamp | null;
  serie_certificado: string | null;
  sujeto_certificado: string | null;
  tipo: string;
  valor_normalizado: string | null;
  vigente_hasta: Timestamp | null;
}

export interface ApiToken {
  activa: Generated<boolean>;
  alcances: Generated<string[]>;
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  cuenta_id: string;
  expira_en: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  prefijo: string;
  revocado_en: Timestamp | null;
  token_sha256: string;
  ultimo_uso_en: Timestamp | null;
  ultimo_uso_ip: string | null;
}

export interface Archivo {
  bytes: Int8;
  clase: string;
  clave_almacenamiento: string;
  creado_en: Generated<Timestamp>;
  cuenta_custodia_id: string;
  id: Generated<string>;
  mime: string;
  paginas: number | null;
  region: string;
  sha256: Buffer;
}

export interface Banco {
  activo: Generated<boolean>;
  codigo: string | null;
  id: Generated<string>;
  nombre: string;
  orden: Generated<number>;
  pais: string;
}

export interface BitacoraPlataforma {
  accion: string;
  actor_tipo: string;
  antes: Json | null;
  /** Null = evento de plataforma, sin cuenta. Ver migración 027. */
  cuenta_id: string | null;
  despues: Json | null;
  id: Generated<string>;
  identidad_id: string | null;
  ip: string | null;
  ocurrido_en: Generated<Timestamp>;
  recurso_id: string | null;
  recurso_tipo: string;
  user_agent: string | null;
}

export interface BloqueMensaje {
  circuito_id: string | null;
  codigo: string;
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  cuenta_id: string;
  cuerpo: string;
  id: Generated<string>;
  idioma: string;
}

export interface Capacidad {
  accion: string;
  descripcion_i18n: Json;
  id: Generated<string>;
  recurso: string;
}

export interface Carpeta {
  creada_en: Generated<Timestamp>;
  creada_por: string | null;
  cuenta_id: string;
  id: Generated<string>;
  nombre_i18n: Json;
  padre_id: string | null;
  ruta: string;
  sistema: string | null;
}

export interface CarpetaPermiso {
  acciones: string[];
  carpeta_id: string;
  creado_en: Generated<Timestamp>;
  cuenta_id: string;
  id: Generated<string>;
  otorgado_por: string | null;
  rol_id: string;
}

export interface Circuito {
  archivo_base_id: string;
  cerrado_en: Timestamp | null;
  creado_en: Generated<Timestamp>;
  creado_por_identidad_id: string;
  cuenta_propietaria_id: string;
  dias_vigencia: number | null;
  enviado_en: Timestamp | null;
  estado: Generated<string>;
  id: Generated<string>;
  idioma: Generated<string>;
  modo: string;
  modo_sello: string | null;
  motivo_cancelacion: string | null;
  nivel_firma: string;
  pais_marco: string;
  permite_delegar: Generated<boolean>;
  politica_idioma: Generated<string>;
  politica_rechazo: Generated<string>;
  prorrogable: Generated<boolean>;
  prorrogas_usadas: Generated<number>;
  titulo: string;
  vence_en: Timestamp | null;
}

export interface ConsumoIa {
  actualizado_en: Generated<Timestamp>;
  costo_base: Generated<Numeric>;
  cuenta_id: string;
  id: Generated<string>;
  input_tokens: Generated<Int8>;
  modelo: string;
  moneda: Generated<string>;
  output_tokens: Generated<Int8>;
  periodo: string;
}

export interface CorreoConfig {
  activa: Generated<boolean>;
  actualizada_en: Generated<Timestamp>;
  creada_en: Generated<Timestamp>;
  host: string;
  id: Generated<string>;
  password_cifrado: string | null;
  proveedor: Generated<string>;
  puerto: Generated<number>;
  remitente_email: string;
  remitente_nombre: string;
  responder_a: string | null;
  seguridad: Generated<string>;
  usuario: string;
}

export interface Credencial {
  bloqueada_hasta: Timestamp | null;
  creada_en: Generated<Timestamp>;
  hash_password: string | null;
  identidad_id: string;
  idp_externo: string | null;
  idp_sujeto: string | null;
  intentos_fallidos: Generated<number>;
  otp_habilitado: Generated<boolean>;
  password_cambiada_en: Timestamp | null;
  telefono_e164: string | null;
  ultimo_acceso_en: Timestamp | null;
}

export interface Cuenta {
  cerrada_en: Timestamp | null;
  creada_en: Generated<Timestamp>;
  en_mora_desde: Timestamp | null;
  estado: Generated<string>;
  estado_cobranza: Generated<string>;
  id: Generated<string>;
  identidad_titular_id: string | null;
  idioma: Generated<string>;
  modo_clave: Generated<string>;
  modo_sello: Generated<string>;
  moneda: string;
  nombre_mostrado: string;
  pais: string;
  plan_id: string | null;
  suspendida_cobranza_desde: Timestamp | null;
  suspendida_en: Timestamp | null;
  tipo: string;
}

export interface DispositivoConfiable {
  anclaje_probado_id: string | null;
  confiado_en: Generated<Timestamp>;
  device_id: string;
  etiqueta: string | null;
  expira_en: Timestamp;
  id: Generated<string>;
  identidad_id: string;
  ip_alta: string | null;
  nivel_garantia: string | null;
  revocado_en: Timestamp | null;
  ultimo_uso_en: Generated<Timestamp>;
  user_agent: string | null;
}

export interface DispositivoConfiableVigente {
  anclaje_probado_id: string | null;
  confiado_en: Timestamp | null;
  device_id: string | null;
  etiqueta: string | null;
  expira_en: Timestamp | null;
  id: string | null;
  identidad_id: string | null;
  ip_alta: string | null;
  nivel_garantia: string | null;
  revocado_en: Timestamp | null;
  ultimo_uso_en: Timestamp | null;
  user_agent: string | null;
}

export interface Empresa {
  actualizada_en: Generated<Timestamp>;
  cuenta_id: string;
  domicilio: string | null;
  identificacion_fiscal: string | null;
  industria_id: string | null;
  razon_social: string;
}

export interface FacturaLinea {
  cantidad: Generated<Numeric>;
  concepto: string;
  detalle_i18n: Json;
  factura_id: string;
  id: Generated<string>;
  monto: Numeric;
  nivel_firma: string | null;
  orden: number;
  precio_unitario: Generated<Numeric>;
  proveedor: string | null;
}

export interface FacturaPlataforma {
  comprobante_externo_id: string | null;
  comprobante_url: string | null;
  creada_en: Generated<Timestamp>;
  cuenta_id: string;
  emitida_en: Timestamp | null;
  estado: Generated<string>;
  id: Generated<string>;
  moneda: string;
  monto_impuestos: Generated<Numeric>;
  monto_neto: Generated<Numeric>;
  monto_total: Generated<Numeric>;
  pagada_en: Timestamp | null;
  periodo: string;
  plan_id: string | null;
  receptor_id_fiscal: string | null;
  receptor_pais: string | null;
  receptor_razon_social: string | null;
  tc_fecha: Timestamp | null;
  tc_fuente: string | null;
  tc_venta_usd: Numeric | null;
  tipo_comprobante: string | null;
  vence_en: Timestamp | null;
}

export interface Identidad {
  anclaje_principal_id: string | null;
  creada_en: Generated<Timestamp>;
  creada_por_cuenta_id: string | null;
  email_mostrado: string;
  email_normalizado: string;
  email_verificado_en: Timestamp | null;
  estado: Generated<string>;
  fusionada_en_id: string | null;
  id: Generated<string>;
  idioma_preferido: string | null;
  nombre_mostrado: string | null;
}

export interface Industria {
  codigo: string;
  id: Generated<string>;
  nombre_i18n: Json;
}

export interface Instancia {
  archivo_firmado_id: string | null;
  cerrada_en: Timestamp | null;
  circuito_id: string;
  creada_en: Generated<Timestamp>;
  cuenta_propietaria_id: string;
  estado: Generated<string>;
  id: Generated<string>;
  numero: number;
  sha256_vigente: Buffer | null;
}

export interface IntegracionFacturacion {
  activa: Generated<boolean>;
  actualizada_en: Generated<Timestamp>;
  api_credencial_cifrada: string | null;
  api_url: string | null;
  archivo_formato: string | null;
  creada_en: Generated<Timestamp>;
  id: Generated<string>;
  modo: Generated<string>;
  pais: string;
  proveedor: string;
}

export interface Marca {
  actualizada_en: Generated<Timestamp>;
  color_primario: string | null;
  color_texto: string | null;
  cuenta_id: string;
  logo: Buffer | null;
  logo_bytes: number | null;
  logo_mime: string | null;
}

export interface MedioPago {
  activo: Generated<boolean>;
  actualizado_en: Generated<Timestamp>;
  banco_id: string | null;
  creado_en: Generated<Timestamp>;
  cuenta_id: string;
  es_default: Generated<boolean>;
  id: Generated<string>;
  marca: string | null;
  moneda: string | null;
  numero_cuenta: string | null;
  pasarela_id: string | null;
  tipo: string;
  tipo_cuenta_id: string | null;
  titular: string | null;
  token_externo: string | null;
  ultimos_cuatro: string | null;
  vence_anio: number | null;
  vence_mes: number | null;
}

export interface Membresia {
  creada_en: Generated<Timestamp>;
  cuenta_id: string;
  desde: Generated<Timestamp>;
  estado: Generated<string>;
  hasta: Timestamp | null;
  id: Generated<string>;
  identidad_id: string;
  persona_id: string | null;
}

export interface Operador {
  activo: Generated<boolean>;
  actualizado_en: Generated<Timestamp>;
  bloqueado_hasta: Timestamp | null;
  creado_en: Generated<Timestamp>;
  es_superadmin: Generated<boolean>;
  id: Generated<string>;
  intentos_fallidos: Generated<number>;
  mfa_habilitado_en: Timestamp | null;
  mfa_secreto: string | null;
  nombre: string;
  password_hash: string;
  usuario: string;
}

export interface OperadorCapacidad {
  capacidad: string;
  operador_id: string;
}

export interface Otorgamiento {
  alcances: string[];
  anclaje_destino_id: string | null;
  circuito_id: string | null;
  condicionado_a_cuenta_id: string | null;
  creado_en: Generated<Timestamp>;
  cuenta_id: string | null;
  cuenta_otorgante_id: string;
  id: Generated<string>;
  identidad_id: string | null;
  instancia_id: string | null;
  irrevocable: Generated<boolean>;
  motivo_revocacion: string | null;
  nivel_garantia_minimo: Generated<string>;
  origen: string;
  otorgado_por: string | null;
  revocado_en: Timestamp | null;
  revocado_por: string | null;
  vigente_desde: Generated<Timestamp>;
  vigente_hasta: Timestamp | null;
}

export interface OtpLogin {
  anclaje_destino_id: string | null;
  canal: Generated<string>;
  codigo_hash: string;
  creado_en: Generated<Timestamp>;
  device_id: string;
  expira_en: Timestamp;
  id: Generated<string>;
  identidad_id: string;
  intentos: Generated<number>;
  ip: string | null;
  usado: Generated<boolean>;
}

export interface Participacion {
  anclaje_usado_id: string | null;
  caracter: Generated<string>;
  circuito_id: string;
  creada_en: Generated<Timestamp>;
  cuenta_propietaria_id: string;
  cuenta_representada_id: string | null;
  delegada_a_id: string | null;
  delegada_por_id: string | null;
  documento_exigido_num: string | null;
  documento_exigido_pais: string | null;
  documento_exigido_tipo: string | null;
  estado: Generated<string>;
  firmada_en: Timestamp | null;
  id: Generated<string>;
  identidad_id: string;
  idioma_declarado: string | null;
  idioma_efectivo: string | null;
  instancia_id: string;
  minimo_requerido: number | null;
  motivo_delegacion: string | null;
  motivo_rechazo: string | null;
  nivel_garantia_minimo: Generated<string>;
  nivel_garantia_obtenido: string | null;
  orden: Generated<number>;
  papel: string;
  proveedor_elegido_id: string | null;
  proveedor_sugerido_id: string | null;
}

export interface PasarelaPago {
  activa: Generated<boolean>;
  actualizada_en: Generated<Timestamp>;
  client_id: string | null;
  client_secret_cifrado: string | null;
  creada_en: Generated<Timestamp>;
  id: Generated<string>;
  modo: Generated<string>;
  nombre: string;
  orden: Generated<number>;
  proveedor: string;
  webhook_secret_cifrado: string | null;
}

export interface PasarelaPais {
  activa: Generated<boolean>;
  es_default: Generated<boolean>;
  moneda: string;
  pais: string;
  pasarela_id: string;
}

export interface Persona {
  apellidos: string | null;
  cargo: string | null;
  creada_en: Generated<Timestamp>;
  cuenta_id: string;
  id: Generated<string>;
  identidad_id: string | null;
  jefe_persona_id: string | null;
  legajo: string | null;
  nombres: string | null;
  unidad_organizativa_id: string | null;
}

export interface Plan {
  activo: Generated<boolean>;
  asistente_ia: Generated<boolean>;
  codigo: string;
  creado_en: Generated<Timestamp>;
  ia_cobra: Generated<boolean>;
  ia_incluido: Generated<Numeric>;
  ia_margen_pct: Generated<Numeric>;
  id: Generated<string>;
  nombre_i18n: Json;
  orden: Generated<number>;
}

export interface PlantillaMensaje {
  activa: Generated<boolean>;
  admite_bloque: Generated<boolean>;
  asunto: string | null;
  canal: string;
  codigo: string;
  creada_en: Generated<Timestamp>;
  cuerpo: string;
  id: Generated<string>;
  idioma: string;
  variables: Generated<string[]>;
  version: Generated<number>;
}

export interface PushSuscripcion {
  auth: string;
  creada_en: Generated<Timestamp>;
  endpoint: string;
  fallos: Generated<number>;
  id: Generated<string>;
  identidad_id: string;
  p256dh: string;
  revocada_en: Timestamp | null;
  ultimo_envio_en: Timestamp | null;
  user_agent: string | null;
}

export interface Rol {
  codigo: string;
  creado_en: Generated<Timestamp>;
  cuenta_id: string | null;
  id: Generated<string>;
  nombre_i18n: Json;
  sistema: Generated<boolean>;
}

export interface RolCapacidad {
  capacidad_id: string;
  rol_id: string;
}

export interface Suscripcion {
  actualizada_en: Generated<Timestamp>;
  asistente_ia: boolean | null;
  creada_en: Generated<Timestamp>;
  cuenta_id: string;
  estado: Generated<string>;
  fin: Timestamp | null;
  ia_cobra: boolean | null;
  ia_incluido: Numeric | null;
  ia_margen_pct: Numeric | null;
  id: Generated<string>;
  inicio: Generated<Timestamp>;
  medio_cobro: Generated<string>;
  moneda: string;
  plan_id: string;
}

export interface TarifaIa {
  creada_en: Generated<Timestamp>;
  id: Generated<string>;
  modelo: string;
  moneda: Generated<string>;
  precio_input_millon: Numeric;
  precio_output_millon: Numeric;
  vigente_desde: Generated<Timestamp>;
  vigente_hasta: Timestamp | null;
}

export interface TipoCuentaBancaria {
  activo: Generated<boolean>;
  codigo: string;
  id: Generated<string>;
  nombre_i18n: Json;
  orden: Generated<number>;
  pais: string;
}

export interface TokenAcceso {
  creado_en: Generated<Timestamp>;
  cuenta_id: string | null;
  expira_en: Timestamp;
  id: Generated<string>;
  identidad_id: string;
  ip_uso: string | null;
  tipo: string;
  token_hash: string;
  usado_en: Timestamp | null;
}

export interface TraduccionOverride {
  actualizado_en: Generated<Timestamp>;
  clave: string;
  idioma: string;
  nota: string | null;
  valor: string;
}

export interface TwilioConfig {
  account_sid: string;
  activa: Generated<boolean>;
  actualizada_en: Generated<Timestamp>;
  auth_token_cifrado: string | null;
  creada_en: Generated<Timestamp>;
  from_sms: string | null;
  from_whatsapp: string | null;
  id: Generated<string>;
  wa_content_sid: string | null;
}

export interface Ubicacion {
  archivada: Generated<boolean>;
  carpeta_id: string;
  circuito_id: string | null;
  creada_en: Generated<Timestamp>;
  cuenta_id: string;
  fijada: Generated<boolean>;
  id: Generated<string>;
  instancia_id: string | null;
  movida_en: Timestamp | null;
  movida_por: string | null;
}

export interface UsuarioRol {
  asignado_en: Generated<Timestamp>;
  asignado_por: string | null;
  cuenta_id: string;
  id: Generated<string>;
  identidad_id: string;
  rol_id: string;
}

export interface DB {
  anclaje_identidad: AnclajeIdentidad;
  api_token: ApiToken;
  archivo: Archivo;
  banco: Banco;
  bitacora_plataforma: BitacoraPlataforma;
  bloque_mensaje: BloqueMensaje;
  capacidad: Capacidad;
  carpeta: Carpeta;
  carpeta_permiso: CarpetaPermiso;
  circuito: Circuito;
  consumo_ia: ConsumoIa;
  correo_config: CorreoConfig;
  credencial: Credencial;
  cuenta: Cuenta;
  dispositivo_confiable: DispositivoConfiable;
  dispositivo_confiable_vigente: DispositivoConfiableVigente;
  empresa: Empresa;
  factura_linea: FacturaLinea;
  factura_plataforma: FacturaPlataforma;
  identidad: Identidad;
  industria: Industria;
  instancia: Instancia;
  integracion_facturacion: IntegracionFacturacion;
  marca: Marca;
  medio_pago: MedioPago;
  membresia: Membresia;
  operador: Operador;
  operador_capacidad: OperadorCapacidad;
  otorgamiento: Otorgamiento;
  otp_login: OtpLogin;
  participacion: Participacion;
  pasarela_pago: PasarelaPago;
  pasarela_pais: PasarelaPais;
  persona: Persona;
  plan: Plan;
  plantilla_mensaje: PlantillaMensaje;
  push_suscripcion: PushSuscripcion;
  rol: Rol;
  rol_capacidad: RolCapacidad;
  suscripcion: Suscripcion;
  tarifa_ia: TarifaIa;
  tipo_cuenta_bancaria: TipoCuentaBancaria;
  token_acceso: TokenAcceso;
  traduccion_override: TraduccionOverride;
  twilio_config: TwilioConfig;
  ubicacion: Ubicacion;
  usuario_rol: UsuarioRol;
}
